---
abstract: 'Simple Global Params Management System'
author:
  - 'Pawel Guspiel <neo@cpan.org>'
build_requires:
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Dry
no_index:
  directory:
    - t
    - inc
provides:
    Params::Dry:
        file: lib/Params/Dry.pm
        version: 1.10
    Params::Dry::Types:
        file: lib/Params/Dry/Types.pm
        version: 1.10
    Params::Dry::Types::Number:
        file: lib/Params/Dry/Types/Number.pm
        version: 1.10
    Params::Dry::Types::Ref:
        file: lib/Params/Dry/Types/Ref.pm
        version: 1.10
    Params::Dry::Types::Object:
        file: lib/Params/Dry/Types/Object.pm
        version: 1.10
    Params::Dry::Types::DateTime:
        file: lib/Params/Dry/Types/DateTime.pm
        version: 1.10
    Params::Dry::Types::String:
        file: lib/Params/Dry/Types/String.pm
        version: 1.10
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  perl: 5.01
version: 1.10
resources: 
    license: http://opensource.org/licenses/artistic-license-2.0.php
    repository: https://github.com/neo77/Params-Dry
distribution_type: module
keywords:
    - params
    - parameters
    - validation
